---
- name: Update and upgrade apt packages
  become: true
  hosts: 192.168.34.206

  tasks:
    - name: Check if apt cache has ever been updated before
      ansible.builtin.stat:
        path: /var/lib/apt/lists/partial
      register: apt_dir_partial
    - name: Update apt cache for the first time
      ansible.builtin.apt:
        update_cache: yes
      when: not apt_dir_partial.stat.exists

    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        upgrade: dist
