---
- name: Monitor UPS status using upsd/upsc
  hosts: GMKTec2
  become: true
  tasks:

    - name: Ensure upsd is installed
      package:
        name: nut
        state: present

    - name: Check if upsd service is running
      service:
        name: nut-server
        state: started
        enabled: true

    - name: Run upsc to get UPS status
      command: upsc meterkast-apc@localhost
      register: upsc_output
      failed_when: upsc_output.rc != 0

    - name: Display UPS status
      debug:
        msg: "{{ upsc_output.stdout_lines }}"
        
    - name: Extract all UPS status flags
      set_fact:
        ups_status_flags: "{{ upsc_output.stdout | regex_findall('ups.status:\\s*(.*)') | first | split(' ') }}"
    
    - name: Alert if UPS is in alarm state
      when: "'ALARM' in upsc_output.stdout"
      debug:
        msg: "⚠️ UPS is in alarm state! UPS status flags: {{ ups_status_flags | join(', ') }}"

    - name: Send Discord alert if ALARM is present
      when: "'ALARM' in ups_status_line"
      community.general.discord:
        webhook_id: "{{ discord_webhook_id }}"
        webhook_token: "{{ discord_webhook_token }}"
        content: "🚨 UPS ALERT: Status contains ALARM! ⚠️ Check immediately."


    - name: Alert if UPS is on battery
      when: "'OB' in upsc_output.stdout"
      debug:
        msg: "⚠️ UPS is running on battery!"

    - name: Alert if UPS is low battery
      when: "'LB' in upsc_output.stdout"
      debug:
        msg: "🔋 UPS battery is low!"
