---
- name: Monitor UPS status using upsd/upsc
  hosts: GMKTec2
  become: true
  tasks:

    - name: Ensure upsd is installed
      package:
        name: nut
        state: present

    - name: Check if upsd service is running
      service:
        name: nut-server
        state: started
        enabled: true
        
    - name: Read previous UPS status
      slurp:
        src: /var/tmp/last_ups_status.txt
      register: previous_status_raw
      ignore_errors: true

    - name: Decode previous status
      set_fact:
        previous_status: "{{ previous_status_raw.content | default('') | b64decode }}"
        
    - name: Run upsc to get UPS status
      command: upsc meterkast-apc@localhost
      register: upsc_output
      failed_when: upsc_output.rc != 0

    - name: Display UPS status
      debug:
        msg: "{{ upsc_output.stdout_lines }}"
        
    - name: Extract all UPS status flags
      set_fact:
        ups_status_flags: "{{ upsc_output.stdout | regex_findall('ups.status:\\s*(.*)') | first | split(' ') }}"

    - name: Extract full UPS status flags
      set_fact:
        ups_status_full: "{{ ups_status_flags | join(', ') }}"
        
    - name: Save current UPS status to file
      copy:
        dest: /var/tmp/last_ups_status.txt
        content: "{{ ups_status_full }}"
        
    - name: Alert if UPS is in alarm state
      when: "'ALARM' in upsc_output.stdout"
      debug:
        msg: "⚠️ UPS is in alarm state! UPS status flags: {{ ups_status_full }}"

    - name: Send Discord alert if ALARM is present
      uri:
        url: "{{ discord_webhook}}"
        method: POST
        body_format: json
        body: '{"content": "🚨 UPS ALERT: Status contains ALARM! UPS status flags: {{ ups_status_full }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when:
        - "'ALARM' in ups_status_full"
        - "'ALARM' not in previous_status"
        
    - name: Send Discord alert if UPS status changed
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body: 
          content: > 
            🔄 UPS status changed! 
            Previous: {{ previous_status }} 
            Current: {{ ups_status_full }}
        headers:
          Content-Type: application/json
        status_code: 204
      when: ups_status_full != previous_status  
      
    - name: Alert if UPS is on battery
      when: "'OB' in upsc_output.stdout"
      debug:
        msg: "⚠️ UPS is running on battery!"

    - name: Alert if UPS is low battery
      when: "'LB' in upsc_output.stdout"
      debug:
        msg: "🔋 UPS battery is low!"
