---
- name: Prune TruenasM GMKTec backups
  hosts: truenas-main
  gather_facts: false

  vars:
    # backup_path: "/mnt/TrueNASPool1/LaptopBackup/GMKtecJoWin11/"
    ### alternate [new] path
    backup_path: "/mnt/BigPool/LaptopBackup/GMKTecG3Plus_Win11_Jo"
    
    ### actual command
    #prune_command: 'sudo ls -1t "{{ backup_path }}" | tail -n +16 | xargs -I{} sudo rm "{{ backup_path }}/{}"'
    ### dry-run command
    prune_command: 'sudo ls -1t "{{ backup_path }}" | tail -n +16 | xargs -I{} echo "{{ backup_path }}/{}"'
    
    show_debug: true

  tasks:
    - name: Debug is enabled
      debug:
        msg: "Debug mode is ON"
      when: (show_debug | default(false)) | bool

    - name: Run active prune command via shell
      shell: "{{ prune_command }}"
      register: prune_output

    - name: Display prune output
      debug:
        msg: "{{ prune_output.stdout_lines }}"
      when: (show_debug | default(false)) | bool

    - name: Send discord message after backup pruning completes
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body:
          content: "Successfully pruned old backups for **{{ inventory_hostname }}** in dataset `{{ backup_path }}`. Kept the 15 most recent backups."
        headers:
          Content-Type: application/json
        status_code: 204
      # This ensures it only runs if the deletion step itself didn't crash
      when: prune_output.rc == 0
