---
- name: Prune TruenasM GMKTec backups
  hosts: truenas-main
  gather_facts: false

  vars:
    # backup_path: "/mnt/TrueNASPool1/LaptopBackup/GMKtecJoWin11/"
    ### alternate [new] path
    backup_path: "/mnt/BigPool/LaptopBackup/GMKTecG3Plus_Win11_Jo"
    
    ### actual command
    prune_command: 'sudo ls -1t "{{ backup_path }}" | tail -n +16 | xargs -I{} sudo rm "{{ backup_path }}/{}"'
    ### dry-run command
    #prune_command: 'sudo ls -1t "{{ backup_path }}" | tail -n +16 | xargs -I{} echo "{{ backup_path }}/{}"'
    
    show_debug: true

  tasks:
    - name: Debug is enabled
      debug:
        msg: "Debug mode is ON"
      when: (show_debug | default(false)) | bool

    - name: Run active prune command via shell
      shell: "{{ prune_command }}"
      register: prune_output

    - name: Display prune output
      debug:
        msg: "{{ prune_output.stdout_lines }}"
      when: (show_debug | default(false)) | bool

    - name: Get post-prune file list (Sorted by Date, Newest First, Human-Readable Sizes)
      shell: "sudo ls -lash -t '{{ backup_path }}' | head -n 20"
      register: ls_output

    - name: Get total directory size
      shell: "sudo du -sh '{{ backup_path }}'"
      register: du_output

    - name: Send detailed discord message
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body:
          content: |
            Successfully pruned old backups for **{{ inventory_hostname }}** in `{{ backup_path }}`!
            **Total Directory Size:** `{{ du_output.stdout.split()[0] }}`
            
            **Remaining Files (Newest First):**
            ```text
            {{ ls_output.stdout }}
            ```
        headers:
          Content-Type: application/json
        status_code: 204
      when: prune_output.rc == 0
