---
- name: Prune DiskstationJo GMKTec backups
  hosts: diskstationjo
  become: true
  gather_facts: false

  vars:
    backup_path: "/volume1/Opslag_Jo/Backups via AOMEI Backupper/GMKTecG3Plus_Win11"
  
    # actual command
    # prune_command: 'ls -1t "{{ backup_path }}" | tail -n +16 | xargs -I{} rm "{{ backup_path }}/{}"'
    # dry-run command
    prune_command: 'ls -1t "{{ backup_path }}" | tail -n +16 | xargs -I{} echo "{{ backup_path }}/{}"'
    show_debug: true


  tasks:
    - name: Debug is enabled
      debug:
        msg: "Debug mode is ON"
      when: (show_debug | default(false)) | bool
      
    - name: Run prune command via raw
      raw: "{{ prune_command }}"
      register: prune_output
      failed_when: prune_output.rc != 0

    - name: Display prune output
      debug:
        msg: "{{ prune_output.stdout_lines }}"
      when: (show_debug | default(false)) | bool

